title: Saad Rajpoot
logo: /assets/profile.jpeg
theme: jekyll-theme-merlot
social:
  twitter: https://twitter.com/yourusername
  facebook: https://facebook.com/yourusername
  instagram: https://instagram.com/yourusername
  linkedin: https://linkedin.com/in/yourusername
  github: https://github.com/yourusername
  youtube: https://youtube.com/c/yourusername
